// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnxykngdpsbgmshtscan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBueHlrbmdkcHNiZ21zaHRzY2FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4OTAzMDYsImV4cCI6MjA1NTQ2NjMwNn0.ooJsndBAorM5CpuOi8Wrla4sLJvdo9YVehwMR32NyOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);